### DISCUSSION TITLE
Lost in the forks :)

### DISCUSSION THREAD

**Discussion by Annakan** [urob/zmk-config#118] [Q&A] [answered]
Hello and thanks you for this approach of configuring ZMK.

I am a new Glove80 user and trying to get my keyboard working with your configuration approach and RGB and sucg.

Long story short it seems your approach  requires a fix (https://github.com/zephyrproject-rtos/zephyr/commit/73d5ecc0c5f5dbb4f237b9eeeae84aabfd0dbbb8) that is , unless I am mistaken, not committed  into main ZMK.

I would like to follow the Moergo Glove80 firmware evolution (https://github.com/darknao/zmk) more closely but, AFAIK, your cherry-pick is not in it.

Am  I wrong in this analysis  ? And  shall  I try to cherry pick again and apply that patch ? Or is there a deeper reason it has not been  applied ?

Thanks a lot for your time.

.X.

PS : To be less cryptic what I need the most is RGB and per layer RGB and as soon as I  `#include <dt-bindings/zmk/rgb_colors.h>` the build blows up:)

**Comment by urob** [comment, marked as answer]
You don't have to swap out the `zmk` branch, you can just specify a `zephyr` branch directly in your `west.yml` which will take precedence over the one imported by Moergo's zmk fork. In fact, that's exactly what I do in the `west.yml` in this repo:
https://github.com/urob/zmk-config/blob/1c0450882ce072e3ec440af3500c5a01f1f969b3/config/west.yml#L47-L61

**Reply by Annakan** [reply]
First thanks for the reply.
I forgot that we have 3 layers here, Zephyr / ZMK + modules and the config, should have paid more attention.

I went to look at the current most advanced Glove80 firmware here https://github.com/darknao/zmk/blob/main/app/west.yml  and noticed that ... they use the exact same reference as you do :  
```yaml
manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zephyr
      remote: zmkfirmware
      revision: v3.5.0+zmk-fixes
      clone-depth: 1
      import:
        name-blocklist:
```
So I should see no difference of behavior when basing my config on yours  or directly from (https://github.com/darknao/zmk) and ... that's the case (after testing).

I still can't activate the RGB since `#include <dt-bindings/zmk/rgb_colors.h>` anywhere in the keymap crash the build,  but I need to investigate more to understand why.

Macro based system are hell to debug  :)
