### DISCUSSION TITLE
Syncing ZMK & module releases

### DISCUSSION THREAD

**Discussion by urob** [urob/zmk-config#85] [Announcements]
Upstream ZMK just tagged its first version-controlled [release](https://github.com/zmkfirmware/zmk/releases/tag/v0.1). I followed suite and added a version control system to my collection of modules and my patched ZMK branch as well.

I am using a collection of [automated workflows](https://github.com/urob/zmk-modules-actions/) to sync the versioning of my repos with upstream. 

- Whenever ZMK releases a new version, an automated workflow runs on each module and tests whether it works with the new release. If it does, a new version of the module is released with matching tags.
- Should I add a breaking change to any module in between ZMK releases that change will live in `main` until the next `minor` (!) ZMK version is released. (Depending on the frequency of `major` ZMK releases I may reconsider and hold off breaking changes until the next `major` release).
- If a change warrants earlier release, I'll add a custom minor tag (e.g., `v0.1+locality` in the `zmk-leader-key` module)
- In any case, any modules are guaranteed to keep working within `minor` releases.
- I will also adopt a similar approach for my own ZMK fork and add matching version tags whenever I rebase on a new ZMK release.

The purpose of the system is that one can simply set a [default `revision`](https://github.com/urob/zmk-config/blob/40ed33d94ec57c44ab9f3388a1fe3d337a681d99/config/west.yml#L23) in the west manifest that ensures that firmware and modules play along nicely and won't break unless one bumps that version. 

For example, the following `west` manifest will fix both the ZMK fork and all modules at version `v0.1`.
```yml
manifest:
  defaults:
    remote: urob
    revision: v0.1

  remotes:
    - name: urob
      url-base: https://github.com/urob

  projects:
    - name: zmk
      import: app/west.yml
    - name: zmk-adaptive-key
    - name: zmk-auto-layer
    - name: zmk-helpers
    - name: zmk-leader-key
      revision: v0.1+locality # this is how one overwrites the default
    - name: zmk-tri-state

  self:
    path: config
```

As long as the default version remains the same, there should no longer be any randomly breaking configurations for folks using my branches with Github Actions.
