### ISSUE TITLE
Attempting to use the local build script errors out

### ISSUE THREAD

**Issue by arilebedey** [urob/zmk-config#30]
Running `./zmk_build.sh` errors with the following output:

```
Building glove80_rh... 
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /workspace/zmk/app
-- ZMK Config directory: /workspace/zmk-config/config
CMake Warning at cmake/ZephyrBuildConfig.cmake:199 (message):
  Failed to locate keymap file!
Call Stack (most recent call first):
  /workspace/zmk/zephyr/cmake/modules/zephyr_default.cmake:22 (find_package)
  /workspace/zmk/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /workspace/zmk/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:15 (find_package)


-- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.10") found components: Interpreter 
-- Cache files will be written to: /root/.cache/zephyr
-- Zephyr version: 3.2.0 (/workspace/zmk/zephyr)
-- Found west (found suitable version "0.14.0", minimum required is "0.7.1")
-- Board: glove80_rh
No board named 'glove80_rh' found.
```
2 things seem to be problematic here:
- Zephyr not seeing the board's config? Although I am running the same code pushed to Github builds successfully
-  Board seems to be unsupported

Here is my `west.yml` file for context (maybe I'm messing up by not specifying the Zephyr version somehow? Note: I have tried adding `-v main` which errors differently):

```
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: urob
      revision: main-with-native-mouse
      import: app/west.yml
  self:
    path: config
```
